Cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import signup, stats
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stats/', stats, name='stats'),
    path('', include('app.urls', namespace='app')),
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('movies', list_movies, name='list_movies'),
    path('movies/<str:category>/', list_movies, name='list_movies_by_category'),
    path('movies/None/<int:pk>/', list_movies, name='list_movies_by_cinema'),
    path('<int:movie_id>/seats', list_seats, name='list_seats'),
    path('seat/reserve/<int:movie_id>/<int:seat_id>', reserve_seat, name='reserve_seat'),
    path('profile/', profile, name='profile'),
    path('ticket_detail/<int:pk>/', ticket_detail, name='ticket_detail'),
    path('movie_comment/<int:pk>', movie_comment, name='movie_comment'),
    path('response_ticket/', response_to_check, name='response_ticket'),
    path('check', create_check, name='check'),
    path('search', search, name='search'),
    path('cinema_list', cinema_list, name='cinema_list'),
]

templates/app/index.html
{% extends 'parent/base.html' %}
{% load app_tags %}
{% block title %} Index {% endblock %}
{% block content %}
    <h2>index</h2>
    <div dir="rtl">
        <div>
            <a href="{% url 'app:cinema_list' %}"><h3>لیست سینما ها:</h3></a>
        </div>
        <div>
            <h3>جدیدترین فیلم ها:</h3>
            {% new_film %}
        </div>
        <div>
            <h3>محبوب ترین فیلم ها:</h3>
            {% popular_movies %}
        </div>
        <div>
            <h3>پرفروش ترین فیلم های اخیر:</h3>
            {% most_selling %}
        </div>
    </div>
    <div>
        <h3> دسته بندی:</h3>
        <a href="{% url 'app:list_movies_by_category' 'طنز' %}">طنز</a><br>
        <a href="{% url 'app:list_movies_by_category' 'عاشقانه' %}">عاشقانه</a><br>
        <a href="{% url 'app:list_movies_by_category' 'خشن' %}">خشن</a><br>
        <a href="{% url 'app:list_movies_by_category' 'انیمیشن' %}">انیمیشن</a><br>
        <a href="{% url 'app:list_movies_by_category' 'سایر' %}">سایر</a><br>
    </div>
{% endblock %}

templates/app/movie_theaters.html
{% extends 'parent/base.html' %}
{% block content %}
<div dir="rtl">
    <h2>لسیت سینماها: </h2>
{% for cinema in cinema %}
    <li><a href="{% url 'app:list_movies_by_cinema' cinema.pk %}">{{ cinema.name }}</a></li>
    {% endfor %}
</div>
{% endblock %}

templates/app/movies.html
{% extends 'parent/base.html' %}
{% block title %} movies {% endblock %}
{% block content %}
<h3>All movies:</h3>
{% if  cinema and movies %}
   <h3>فیلم های موجود برای سینما {{cinema}}</h3>
{% endif %}
<ul>{% if  movies %}
    {% for movie in movies %}
        <li><a href="{% url 'app:list_seats' movie.id %}">{{ movie.title }}</a></li>
            {% if movie.pop %}
                <img src="{{ movie.image.url }}">
            {% endif %}
    {% endfor %}
    {% elif category %}
         <p>فیلمی برای دسته بندی {{category}} موجود نمیباشد</p>
    {% else %}
        <p>فیلمی موجود نمیباشد</p>
    {% endif %}
</ul>
{% endblock %}

templates/app/profile.html
{% extends 'parent/base.html' %}
{% block content %}
<form dir="rtl">
    <h2> profile </h2>
    <h3> عزیز{{ user.first_name }}</h3>
    <h4>بلیط های شما: </h4>
    {% for ticket in tickets %}
        <a href="{% url 'app:ticket_detail' ticket.id %}"> {{ ticket.movie.title }} ({{ ticket.seat}}) </a><br>
    {% endfor %}
</form>
{% endblock %}

templates/app/response-check.html
{% extends 'parent/base.html' %}
{% block content %}
<h2> response to your ticket: </h2>
<div dir="">
    {% for ticket in tickets %}
        <p> your ticket: {{ ticket.body }}</p><br>
        {% for response in ticket.check_responses.all %}
            <p> response: {{ response.body }} </p><br>
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}

templates/app/search.html
{% for movie in movies %}
    <ul>
        <a href="{{ movie.get_absolute_url }}"><li> {{movie.title}} </li></a>
    </ul>
{% endfor %}

templates/app/seats.html
{% extends 'parent/base.html' %}
{% block title %} movie_detail {% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
    توضیحات:
{{movie.description}}<br>
    تاریخ پخش:
    {{movie.play_time}}
<h3>Seats available for this movie:</h3>
<ul>
    {% if seats.count == 0 %}
        <li>sold out!</li>
    {% endif %}
    {% for seat in seats %}
        <li><a href="{% url 'app:reserve_seat' movie.id seat.id %}">Seat {{ seat.number }}</a></li>
    {% endfor %}
</ul>

<h2>comments</h2>
{% for comment in comments%}
    {{comment.name}}: {{ comment.body }}<br>
    {% for response in comment.comment_responses.all %}
        <p>{{response.name}}: {{response.body }}</p>
    {% endfor %}
{% endfor %}
<form method="post" action="{% url 'app:movie_comment' movie.id %}">
  <h2> comment-form</h2>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="send" name="comment">
</form>
{% endblock %}

templates/app/ticket_detail.html
{% extends 'parent/base.html' %}
{% block content %}
<h2> Ticket detail </h2>
  <span> {{ ticket.movie.title }}</span><br>
  <span> {{ticket.movie.release_year}} </span><br>
  <span> {{ ticket.movie.play_time }} </span><br>
  <span> </span>
  <span> {{ ticket.seat }}</span>
{% endblock %}