Cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import signup, stats
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stats/', stats, name='stats'),
    path('', include('app.urls', namespace='app')),
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('movies', list_movies, name='list_movies'),
    path('movies/<str:category>/', list_movies, name='list_movies_by_category'),
    path('movies/None/<int:pk>/', list_movies, name='list_movies_by_cinema'),
    path('<int:movie_id>/seats', list_seats, name='list_seats'),
    path('seat/reserve/<int:movie_id>/<int:seat_id>', reserve_seat, name='reserve_seat'),
    path('profile/', profile, name='profile'),
    path('ticket_detail/<int:pk>/', ticket_detail, name='ticket_detail'),
    path('movie_comment/<int:pk>', movie_comment, name='movie_comment'),
    path('response_ticket/', response_to_check, name='response_ticket'),
    path('check', create_check, name='check'),
    path('search', search, name='search'),
    path('cinema_list', cinema_list, name='cinema_list'),
]

templates/partials/header.html
<form method="get" action="{% url 'app:search' %}" dir="rtl">
    <input type="search" name="query" placeholder="جستجو">
    <button type="submit"> جستجو</button>
</form>

templates/partials/navigation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/partials/new_films.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for movie in movies %}
      <a href="{{ movie.get_absolute_url}}">{{movie }}</a><br>
    {% endfor %}
</body>
</html>

templates/partials/popular_movies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for movie in movies %}
    <a href="{{ movie.get_absolute_url}}">{{movie }}</a><br>
    {% endfor %}
</body>
</html>

templates/partials/sell_movies.html
<div>
    {% for movie in top_movie %}
        <a href="{{ 'app:movie.get_absolute_url' movie.id }}"> {{ movie.title }}</a>
        <br>
    {% endfor %}
</div>